site_name: SS-Courses
theme:
  name: material
  extra_css:
    - stylesheets/extra.css
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Bienvenida: index.md
  - Presentación: presentacion.md
  - '1. Modelos Mentales':        # Este será el título del menú desplegable
      - 1.1 ¿Quiénes son mis aprendices?: 1_modelos_mentales/1-1_quienes_son_mis_aprendices.md
      - 1.2 La mente del aprendiz: 1_modelos_mentales/1-2_la_mente_del_aprendiz.md
  - '2. Las entrañas de Swirlify': 
      - 2.1 Tuerca, tornillo y archivo: 2_entranas/2-1_archivos_directorios.md
      - 2.2 Ejemplo GEOCHIP-R: 2_entranas/2-2_geochip-r.md