site_name: SS-Courses
theme:
  name: material
  extra_css:
    - stylesheets/extra.css
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Bienvenida: index.md
  - Presentación: presentacion.md
  - '1 Modelos Mentales':        # Este será el título del menú desplegable
      - 1.1 ¿Quiénes son mis estudiantes?: 1_modelos_mentales/1-1_quienes_son_mis_estudiantes.md
      - 1.2 La mente del aprendiz: 1_modelos_mentales/1-2_la_mente_del_aprendiz.md